from fpdf import FPDF
import os

class HCADFormService:
    def generate_form_41_44(self, property_data: dict, protest_data: dict, output_path: str):
        """
        Generates a simplified version of HCAD Form 41.44 (Notice of Protest).
        """
        pdf = FPDF()
        pdf.add_page()
        
        # Header
        pdf.set_font("Helvetica", 'B', 16)
        pdf.cell(0, 10, "Form 41.44: Property Tax Notice of Protest", ln=True, align='C')
        pdf.set_font("Helvetica", size=10)
        pdf.cell(0, 10, "Appraisal Review Board for the Harris Central Appraisal District", ln=True, align='C')
        pdf.ln(10)
        
        # Section 1: Property Description
        pdf.set_fill_color(230, 230, 230)
        pdf.set_font("Helvetica", 'B', 12)
        pdf.cell(0, 10, " STEP 1: Property Description ", ln=True, fill=True)
        pdf.set_font("Helvetica", size=10)
        pdf.cell(0, 8, f"Account Number: {property_data.get('account_number')}", ln=True)
        pdf.cell(0, 8, f"Property Address: {property_data.get('address')}", ln=True)
        pdf.ln(5)
        
        # Section 2: Reason for Protest
        pdf.set_font("Helvetica", 'B', 12)
        pdf.cell(0, 10, " STEP 2: Reason for Protest ", ln=True, fill=True)
        pdf.set_font("Helvetica", size=10)
        pdf.cell(0, 8, "[X] Incorrect appraised (market) value", ln=True)
        pdf.cell(0, 8, "[X] Value is unequal compared with other properties", ln=True)
        pdf.cell(0, 8, "[ ] Other: __________________________________________", ln=True)
        pdf.ln(5)
        
        # Section 3: Evidence Summary
        pdf.set_font("Helvetica", 'B', 12)
        pdf.cell(0, 10, " STEP 3: Evidence & Narrative Summary ", ln=True, fill=True)
        pdf.set_font("Helvetica", size=10)
        pdf.multi_cell(0, 8, txt=protest_data.get('narrative', 'N/A'))
        pdf.ln(5)
        
        # Footer / Signature
        pdf.ln(20)
        pdf.set_font("Helvetica", 'I', 8)
        pdf.cell(0, 10, "Generated by Texas Equity AI automate platform. This is a computer-generated summary for protest purposes.", ln=True)
        pdf.cell(100, 10, "Signature: __________________________________________", ln=False)
        pdf.cell(0, 10, "Date: ____________________", ln=True)
        
        pdf.output(output_path)
        return output_path
